site_name: Peng-Hsuan Li
pages:
    - Bio: index.md
    - Project: project.md
    - Publication: publication.md
    - Presentation: presentation.md
theme:
    name: readthedocs
    custom_dir: custom_theme/
