# site_url: ""
# use_directory_urls: false
# plugins: []

site_name: Peng-Hsuan Li
nav:
    - Bio: index.md
    - Project: project.md
    - Publication: publication.md
    - Presentation: presentation.md
theme:
    name: readthedocs
    custom_dir: custom_theme/
